name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Zip dist folder
        run: zip -r dist.zip .vitepress/dist/

      - name: Run semantic-release dry-run
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release --dry-run

      - name: Commit release artifacts
        run: |
          git config user.name "semantic-release[bot]"
          git config user.email "bot@users.noreply.github.com"
          git checkout -b release-pr-branch
          git add CHANGELOG.md package.json
          git commit -m "chore: release artifacts [skip ci]" || echo "No changes to commit"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "chore: release artifacts [skip ci]"
          title: "chore: release artifacts"
          body: "This PR contains release-related files generated by semantic-release."
          branch: release-pr-branch
          base: main
          delete-branch: true
          labels: automated pr

      - name: Auto merge PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:release-pr-branch`,
              state: 'open'
            });
            if (prs.data.length > 0) {
              const pr = prs.data[0];
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'squash'
              });
              console.log(`Merged PR #${pr.number}`);
            } else {
              console.log("No matching PR found");
            }
